from django.urls import path
from . import views

urlpatterns = [
    path('auth/login/', views.api_login, name='api_login'),
    path('auth/signup/', views.api_signup, name='api_signup'),
    path('logout/', views.api_logout, name='api_logout'),
    path('auth/validate/', views.api_validate_token, name='api_validate_token'),
    path('change-password/', views.api_change_password, name='api_change_password'),
    path('dashboard/', views.portal_dashboard, name='portal_dashboard'),
    path('documents/upload/', views.upload_document, name='upload_document'),
    path('documents/', views.get_documents, name='get_documents'),
    path('messages/', views.get_messages, name='get_messages'),
    path('messages/send/', views.send_message, name='send_message'),
    path('messages/<int:message_id>/read/', views.mark_message_read, name='mark_message_read'),
    path('documents/<int:document_id>/delete/', views.delete_document, name='delete_document'),
    path('documents/types/', views.get_document_types, name='get_document_types'),
    path('documents/<int:document_id>/download/', views.download_document, name='download_document'),
    path('documents/upload/', views.api_upload_document, name='api_upload_document'),
    path('statements/', views.get_fee_statements, name='get_fee_statements'),
    path('statements/summary/', views.get_statement_summary, name='get_statement_summary'),
    path('statements/upload/', views.upload_fee_statement, name='upload_fee_statement'),
    path('statements/<int:statement_id>/download/', views.download_statement, name='download_statement'),
    path('statements/years/', views.get_years, name='get_years'),
    path('payments/', views.get_payments, name='get_payments'),
    path('payments/summary/', views.get_payment_summary, name='get_payment_summary'),
    path('payments/upload/', views.upload_receipt, name='upload_receipt'),
    path('payments/<int:payment_id>/download/', views.download_receipt, name='download_receipt'),
    path('payments/methods/', views.get_payment_methods, name='get_payment_methods'),
    path('academics/summary/', views.get_academic_summary, name='get_academic_summary'),
    path('academics/subject/<str:subject>/history/', views.get_subject_history, name='get_subject_history'),
    path('academics/grade-guide/', views.get_grade_guide, name='get_grade_guide'),
    path('academics/report-card/<int:summary_id>/download/', views.download_report_card, name='download_report_card'),
    path('messages/', views.get_messages, name='get_messages'),
    path('messages/send/', views.send_message, name='send_message'),
    path('messages/<int:message_id>/read/', views.mark_message_read, name='mark_message_read'),
    path('messages/<int:message_id>/delete/', views.delete_message, name='delete_message'),
    path('profile/', views.api_get_user_profile, name='api_get_user_profile'),
    path('profile/update/', views.api_update_profile, name='api_update_profile'),
    path('profile/image/upload/', views.api_upload_profile_image, name='api_upload_profile_image'),
    path('profile/academic-stats/', views.api_get_academic_stats, name='api_get_academic_stats'),
]