# Generated by Django 6.0 on 2025-12-27 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_deadline_document_financialaid_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('school', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('paid', 'Fully Paid'), ('partial', 'Partial Payment'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('statement_file', models.FileField(blank=True, null=True, upload_to='fee_statements/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'term'],
                'unique_together': {('user', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/%d/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='base.feestatement')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
