# Generated by Django 6.0 on 2025-12-27 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_feestatement_options_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('english', 'English'), ('kiswahili', 'Kiswahili'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('history', 'History'), ('geography', 'Geography'), ('cre', 'CRE'), ('ire', 'IRE'), ('hre', 'HRE'), ('computer', 'Computer Studies'), ('business', 'Business Studies'), ('agriculture', 'Agriculture'), ('home_science', 'Home Science'), ('art', 'Art & Design'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('foreign_language', 'Foreign Language')], max_length=50)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(choices=[('A', 'A (75-100%)'), ('A-', 'A- (70-74%)'), ('B+', 'B+ (65-69%)'), ('B', 'B (60-64%)'), ('B-', 'B- (55-59%)'), ('C+', 'C+ (50-54%)'), ('C', 'C (45-49%)'), ('C-', 'C- (40-44%)'), ('D+', 'D+ (35-39%)'), ('D', 'D (30-34%)'), ('D-', 'D- (25-29%)'), ('E', 'E (0-24%)')], max_length=2)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('report_card', models.FileField(blank=True, null=True, upload_to='report_cards/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['-year', 'term', 'subject'],
                'unique_together': {('user', 'term', 'year', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AcademicSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_grade', models.CharField(max_length=2)),
                ('total_points', models.IntegerField()),
                ('mean_grade', models.CharField(max_length=5)),
                ('class_rank', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('attendance_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Summary',
                'verbose_name_plural': 'Academic Summaries',
                'ordering': ['-year', 'term'],
                'unique_together': {('user', 'term', 'year')},
            },
        ),
    ]
