# Generated by Django 6.0 on 2025-12-29 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_userprofile_options_userprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_key', models.CharField(choices=[('pre_school', 'Pre-School'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('university', 'University/College'), ('vocational', 'Vocational')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='school', max_length=50)),
                ('color_gradient', models.CharField(default='from-blue-500 to-cyan-500', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GradeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('male_students', models.IntegerField(default=0)),
                ('female_students', models.IntegerField(default=0)),
                ('average_performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Statistics',
                'verbose_name_plural': 'Grade Statistics',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='base.educationlevel'),
        ),
        migrations.CreateModel(
            name='EducationLevelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('pending_verification', models.IntegerField(default=0)),
                ('new_this_month', models.IntegerField(default=0)),
                ('average_performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passing_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_aid_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_documents', models.IntegerField(default=0)),
                ('approved_documents', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='base.educationlevel')),
            ],
            options={
                'verbose_name': 'Education Level Statistics',
                'verbose_name_plural': 'Education Level Statistics',
            },
        ),
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='base.educationlevel')),
            ],
            options={
                'verbose_name': 'Grade/Class',
                'verbose_name_plural': 'Grades/Classes',
                'ordering': ['education_level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='base.gradeclass'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['education_level', 'grade_class'], name='base_userpr_educati_c17c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['sponsorship_status'], name='base_userpr_sponsor_b9707e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['county'], name='base_userpr_county_f07271_idx'),
        ),
        migrations.AddField(
            model_name='gradestats',
            name='grade_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='base.gradeclass'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeclass',
            unique_together={('education_level', 'name')},
        ),
    ]
